language: objective-c

before_install:
  - echo "**** before install ****"
  - brew update
  - echo `which python`
  - echo `which git`

install:
  - echo "**** install ****"
  - brew install python
  - git clone -b v3 https://github.com/cocos2d/cocos2d-console.git $HOME/cocos2d-console

before_script:
  - echo "**** before_script ****"
  - export COCOS_CONSOLE_ROOT="$HOME/cocos2d-console/bin"
  - export PATH="$COCOS_CONSOLE_ROOT:$PATH"
  - echo env
  - echo `ls $COCOS_CONSOLE_ROOT`

script:
  - echo "**** script ****"
  - cocos --src src --dst dst
