language: objective-c

branches:
  only:
    - master

before_install:
  - echo "**** before install ****"
  - brew update
  - echo `python --version`
  - echo `git --version`

install:
  - echo "**** install ****"
  - brew install ant
  - brew install closure-compiler
  - git clone -b v3 https://github.com/cocos2d/cocos2d-console.git $HOME/cocos2d-console
  - echo `ant -version`
  - echo `which ant`

before_script:
  - echo "**** before_script ****"
  - echo `pwd`
  - export COCOS_CONSOLE_ROOT="$HOME/cocos2d-console/bin"
  - export PATH="$COCOS_CONSOLE_ROOT:$PATH"
  - export ANT_ROOT="/usr/local/bin"
  - env
  - echo `ls $COCOS_CONSOLE_ROOT`

script:
  - echo "**** script ****"
  - echo "no" | cocos compile --platform web --source-map --advanced --verbose
  - echo `ls -l runtime/html5`

after_success:
  - echo "**** after success ****"
  - pushd $HOME
  - (git clone git://github.com:$TRAVIS_REPO_SLUG.git html --reference $TRAVIS_BUILD_DIR -b gh-pages) || (git clone git://github.com:$TRAVIS_REPO_SLUG.git html --reference $TRAVIS_BUILD_DIR && cd gh-pages && git checkout --orphan gh-pages && git rm -rf .)
  - pushd html
  - mv $TRAVIS_BUILD_DIR/runtime/html5/* .
  - git add .
  - git commit -a -m "Built by $TRAVIS_COMMIT"
  - git push --quiet https://$GH_TOKEN@github.com/traviscitest.git gh-pages 2> /dev/null
  - popd
  - popd
