language: objective-c

before_install:
  - echo "**** before install ****"
  - brew update
  - echo `python --version`
  - echo `git --version`
  - echo `ant -version`
  - echo `which ant`

install:
  - echo "**** install ****"
  - brew install closure-compiler
  - git clone -b v3 https://github.com/cocos2d/cocos2d-console.git $HOME/cocos2d-console

before_script:
  - echo "**** before_script ****"
  - echo `pwd`
  - export COCOS_CONSOLE_ROOT="$HOME/cocos2d-console/bin"
  - export PATH="$COCOS_CONSOLE_ROOT:$PATH"
  - env
  - echo `ls $COCOS_CONSOLE_ROOT`

script:
  - echo "**** script ****"
  - echo "no" | cocos compile --platform web --source-map --advanced --verbose
  - echo `ls -l runtime/html5`
