language: objective-c

before_install:
  - echo "**** before install ****"
  - brew update
  - echo `python --version`
  - echo `git --version`

install:
  - echo "**** install ****"
  - git clone -b v3 https://github.com/cocos2d/cocos2d-console.git $HOME/cocos2d-console

before_script:
  - echo "**** before_script ****"
  - echo `pwd`
  - export COCOS_CONSOLE_ROOT="$HOME/cocos2d-console/bin"
  - export PATH="$COCOS_CONSOLE_ROOT:$PATH"
  - env
  - echo `ls $COCOS_CONSOLE_ROOT`

script:
  - echo "**** script ****"
  - cocos compile --platform web --src $TRAVIS_BUILD_DIR --dst web
