language: objective-c

sudo: false

cache:
  directories:
    - /usr/local

env:
  global:
    - GIT_COMMITTER_NAME=niku
    - GIT_COMMITTER_EMAIL=niku@niku.name
    - GIT_AUTHOR_NAME=niku
    - GIT_AUTHOR_EMAIL=niku@niku.name
    - secure: "MVujlkd82//ppLZqkpAXb09b9JdUNto9uWCrgy2S5L+htAwoRfsrYKG/qoUVdy+viVCb8iNMgo6Xb/Ap16XKuc2kKhCtGAenbYqpO9Y/OZdOMF6a4ds6dmPaBngHBs6FoIMjH3l7MqF7cPzAKq5bbTr9rtTBnl40VCOWrsKQ9uM="

branches:
  only:
    - master

before_install:
  - brew update

install:
  - brew install ant
  - brew install closure-compiler
  - git clone https://github.com/cocos2d/cocos2d-console.git $HOME/cocos2d-console -b v3

before_script:
  - export COCOS_CONSOLE_ROOT="$HOME/cocos2d-console/bin"
  - export PATH="$COCOS_CONSOLE_ROOT:$PATH"
  - export ANT_ROOT="/usr/local/bin"

script:
  - echo "no" | cocos compile --platform web --source-map --advanced --verbose
  - ls runtime/html5

after_success:
  - (git clone git://github.com/$TRAVIS_REPO_SLUG.git $HOME/html --reference $TRAVIS_BUILD_DIR -b gh-pages) || (git clone git://github.com/$TRAVIS_REPO_SLUG.git $HOME/html --reference $TRAVIS_BUILD_DIR && pushd $HOME/html && git checkout --orphan gh-pages && git rm -rf .)
  - mv runtime/html5/* $HOME/html
  - cd $HOME/html && git add . && git commit -a -m "Built by $TRAVIS_COMMIT" && git push https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git gh-pages
